name: Release Drafter
on:
  push:
  workflow_dispatch:
  release:
# Only allow 1 release-drafter build at a time to avoid creating multiple "next" releases
concurrency: "release-drafter"
jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
      - uses: release-drafter/release-drafter@3f0f87098bd6b5c5b9a36d49c41d998ea58f9348 # v5
        env:
          # This token is generated automatically by default in GitHub Actions: no need to create it manually
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
